### ISSUE TITLE
Make "bw /unlock <password>" not showing the plain text password

### ISSUE THREAD

**Issue by Marcel1802** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#14]
## Problem:

When unlocking the vault, you have to enter your password into the Flow Launcher.
You plain text password stands in the middle of your screen while logging in which is a problem when not being in a private area.

## Possible fix:

Show ```*****``` instead of the password.

## Alternative fix:

You can get a bitwarden session key via  CLI (```bw login --raw```).
Being able to use a session key for authentication would be nice.
It would be even better not to enter the key directly but to use an environment variable where the session key is read from.
So you save your session key in the environment variable e.g. ```BW_SESSION``` and the plugin reads the key from it.

**Comment by RedMageKnight** [comment]
The session key is used to manage the timeout periods and auto-authentication when a user designates to never expire out the session. This is how it is maintained and is already in place. 

I'm aware of the obfuscated password being a desired improvement, however, Flow Launcher does not have the ability to set a data type in the search bar so I cannot set it adhoc as the user enters the /unlock sub command. I've been meaning to look into ways I can adjust the input text programmatically by swapping out the characters of the password once the user enters the subcommand but ran into some issues capturing the true value the first time I tried this. I will look into this again when I have some time.

**Comment by RedMageKnight** [comment]
Opened as project item.
