### ISSUE TITLE
Bitwarden /unlock not working - Two-step login Enabled

### ISSUE THREAD

**Issue by hdecoded** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#18]
Hi @RedMageKnight 

Firstly many thanks for making this plugin. I have been waiting for long time to have Bitwarden plugin for flow launcher. 

I installed the plugin and followed the instructions to login but getting the following error.

```
Unlock Failed 

Failed to unlock the vault. Please check your master password and try again.
```

I have gone through the issues and found out that #4 isssue is exactly what I am facing. I tried placing the session key in the json as mentioned [here](https://github.com/RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch/issues/4#issuecomment-2264345746) but the moment I enter my password the session key is being updated.

I noticed a weird pattern with the keys that are being generated 

CLI is consistently pushing out 88 char keys but the plugin keys are (93&98) varying in length, I compared them and looks like the char **`+`** is being printed as **`\u002B`**

Hope this helps and please let me know if you need any other help I will be happy to test and report.

**Comment by tagoh** [comment]
I see same issue here.  Updated JSON file by the hand will be backed up once Flow Launcher runs and then `+` will be replaced with `\u002B` in new JSON file.

**Comment by RedMageKnight** [comment]
Hi @tagoh,

Thank you for your report - I went ahead and pushed a quick patch in version 1.3.2. When this gets updated in the extension store, please use this version and let me know how it goes. Some things changed in my unlock logic with later versions of the CLI.

**Comment by hdecoded** [comment]
Got the update. Its working now.
