### ISSUE TITLE
Plugin doesn't ask for MP when copying passwords that require so

### ISSUE THREAD

**Issue by jeregon1** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#20]
Thank you so much for such a brilliant plugin.

However, you know you can enable MP prompt for certain cards, logins... Just as on the web or the browser extension, but it doesn't work on this plugin. I think you have the infrastructure since there's already a MP prompt window done, so I hope it doesn't take you much time.

Need more info?

**Comment by RedMageKnight** [comment]
Hi @jeregon1,

Sure! I'm looking into this now - having the CLI respond to verification prompts has been proving a bit tricky but I'm working through it and will update you once I've completed it. Thank you for bringing this to my attention, I've never used this feature before so I didn't think about it while developing it.

**Comment by jeregon1** [comment]
No problem, I just use it for money accounts to overkill the security hahaha

**Comment by RedMageKnight** [comment]
This feature should now be available in version 2.1.0. Once you are able to update the plugin from the store, go ahead and give it a go and let me know how it goes.

**Comment by jeregon1** [comment]
Amazing, it works as expected, I'm so grateful :)
