### ISSUE TITLE
feat: unlock vault with PIN/Windows Hello

### ISSUE THREAD

**Issue by talhabw** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#8]
Since we create long and secure passwords, it is not really feasible to unlock by writing it each time. Not locking is also not feasible because access to computer shouldn't be equal to access to every single password of mine. 

I am not sure if the API will allow this or not, but it would be great to unlock vault via a PIN. I don't think Windows Hello thing will be possible but, if it is, it would be great too.

**Comment by RedMageKnight** [comment]
As far as I've been able to tell from review of the API, this is not possible through CLI, only their full clients (including the extension). This was requested back as early as 2021 as far as I can tell (probably earlier) but was never implemented.
