### ISSUE TITLE
Add subactions to each item to copy username/TOTP...

### ISSUE THREAD

**Issue by Chaoscontrol** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#9]
I know there are keyboard shortcuts for these, but I struggle to keep remembering shortcuts for all my actions. 

It'd be nice to have as an alternative each of the subactions after right clicking on a particular item, just like some other plugins and Flow does. 

Just a small UX improvement. :) Thanks for the great plugin.

**Comment by Chaoscontrol** [comment]
Sure, here you go. It's not any specific plugin I think. The default ones have it, like Explorer. 

![image](https://github.com/user-attachments/assets/d362e1a3-5732-4edd-ab7e-1b274f0e234b)
![image](https://github.com/user-attachments/assets/7d684403-174e-45ad-96cf-a5cbfedca011)

**Comment by abbasou** [comment]
Upvote to this. Navigating the submenu using right and left arrows to access different actions would a great improvement. Copying different fields, even updating passwords, etc.

**Comment by RedMageKnight** [comment]
I had no idea you could even navigate left and right to access submenus, I guess I've been using Flow Launcher way too basically!

Thanks for the info, I'll take a look and see what I can do :)

**Comment by RedMageKnight** [comment]
Added to project.
